### ISSUE TITLE
Selector Aliases

### ISSUE THREAD

**Issue by ItsNickBarry** [mudgen/diamond-3#14]
For true interoperability of facets written and deployed by different authors, it would be useful if selectors could be aliased.  For example, both a whitelist and a role management contract might have a function with the signature `add(address)`.

As this would likely be a rare occurrence, the best implementation might be an `AliasFacet` contract, whose fallback function handles the routing of selector aliases to the target facets.  The `Diamond` fallback would therefore remain gas-efficient.

**Comment by mudgen** [comment]
@ItsNickBarry I am interested in this.  But I don't understand what you are saying. Can you explain more?

> As this would likely be a rare occurrence

What would be a rare occurrence?

>  selector aliases to the target facets

What are selector aliases?

**Comment by ItsNickBarry** [comment]
The issue is that two different functions with the same signature cannot be added to a diamond.  This might present a barrier to the development of a wide variety of interoperable third-party facet contracts.  Though selector collisions would be rare because a competent facet contract author would try to use descriptive, unique function names.

Here's an example of how selector aliases might work:

Imagine that facets `A` and `B` both have a function `run()`.  Both `run()` functions could not be added to a diamond using `diamondCut`.

```solidity
contract AliasFacet {
  bytes32 private constant DIAMOND_STORAGE_POSITION = keccak256('AliasFacet');

  struct DiamondStorage {
    mapping (bytes4 => bytes4) selectorAliases;
    mapping (bytes4 => address) aliasAddresses;
  }

  fallback () {
    bytes4 alias = _diamondStorage().selectorAliases[msg.sig];
    address target = _diamondStorage().aliasAddresses[alias];

    // TODO: delegatecall to target with `alias` selector and msg.data
  }

  function aliasCut (bytes4 selector, bytes4 alias, address target) external {
    _diamondStorage().selectorAliases[selector] = alias;
    _diamondStorage().aliasAddresses[alias] = target;
  }

  function _diamondStorage () private pure returns (DiamondStorage storage ds) {
    bytes32 position = DIAMOND_STORAGE_POSITION;
    assembly { ds.slot := position }
  }
}
```

One or both functions could be added using aliases, such as `runA()` and `runB()`.

```solidity
interface AliasedFunctions {
  function runA () external;
  function runB () external;
```

Add `aliasCut` to the diamond using `diamondCut`.

Setup the aliases by calling `aliasCut`:

```solidity
diamond.aliasCut(A.run.selector, AliasedFunctions.runA.selector, A.address);
diamond.aliasCut(B.run.selector, AliasedFunctions.runB.selector, B.address);
```

Add the aliases to the diamond using `diamondCut` (for simplicity, let's pretend that `diamondCut` has the signature `(bytes4 selector, address facet)` and adds one function to the diamond at a time):

```solidity
diamond.diamondCut(AliasedFunctions.runA.selector, AliasFacet.address);
diamond.diamondCut(AliasedFunctions.runB.selector, AliasFacet.address);
```

**Comment by mudgen** [comment]
Cool.  I like this idea.  I would like to see something like this implemented with a diamond.
