### ISSUE TITLE
Fallback Fallback

### ISSUE THREAD

**Issue by ItsNickBarry** [mudgen/diamond-3#15]
It is conceivable that the author of a Diamond contract might wish to implement a custom fallback function, but the current design does not allow this.

A possible implementation would allow a fallback `address` to be set rather than a `function`.  This address would contain code that itself implements a fallback function.

**Comment by mudgen** [comment]
Good point.  I updated EIP-2535 Diamond Standard with this text in the [implementation points section](https://eips.ethereum.org/EIPS/eip-2535#implementation-points):

> When a function is called on a diamond it executes immediately if it is an “immutable function” defined directly in the diamond. Otherwise the diamond’s fallback function is executed. The fallback function finds the facet associated with the function and executes the function using delegatecall. If there is no facet for the function and no other mechanism to handle it then execution reverts.

More specifically I added/changed this part:

> If there is no facet for the function and no other mechanism to handle it then execution reverts.

This makes the standard more flexible so people can create and use other mechanisms besides the function selector to facet address mapping.
