### ISSUE TITLE
Upgrading structure in library

### ISSUE THREAD

**Issue by stanta** [mudgen/diamond-3#27]
Hi, Nick! 
Brilliant conception, awesome ideas!
Did you tested next case:
1. we deploy LibDiamond.sol as separate library 
2. we linking this to Diamond.sol
3. add some datas
4. NEXT - adding or changing structure in  LibDiamond.sol  (adding new variables, changing old)
5. deploying this again and link to existing Diamond.sol. 
Question 1  is it possible?)
Question2 - have it backward compatibility? So can "old" stored data  form p.3 be accessed/modified through  new, changed in p.4 structure?

**Comment by stanta** [comment]
Ok, thank you! I thing now about vice-versa variant - store all datas in "facets". It promise real flexibility of data structures.

Another question about selectorToFacetAndPosition function. Do I understand right, that it  can't recognize  function with same name and arguments from different facets, any function in whole diamond shall have unique name or argument list?

**Comment by mudgen** [comment]
@stanta:

> Another question about selectorToFacetAndPosition function. Do I understand right, that it can't recognize function with same name and arguments from different facets, any function in whole diamond shall have unique name or argument list?

Yes, you are correct about this. Generally a diamond cannot have two external functions with the same name and arguments. There can be different functions with the same name but different arguments.
