### ISSUE TITLE
Possible Simplification with Fallback Function

### ISSUE THREAD

**Issue by mudgen** [mudgen/diamond-3#8]
Maybe the implementation of the fallback would be simpler if I used:  `address.delegatecall(msg.data)` instead of assembly.  I would need to test to see if it uses more gas.

**Comment by WyseNynja** [comment]
I just experimented with this and ran into this blocker:

```
TypeError: Return values for fallback functions are not yet implemented.
```

**Comment by mudgen** [comment]
Interesting thanks.  I see I would have to drop to assembly to return the value.
